### PR TITLE
feature: Brutal prototype of the form builder

### PR DESCRIPTION
**Pull request by foresttoney**
Ignore the quality of the code -- it obviously is horrible. But, this PR implements proofs out building a form config with a live rendering preview.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
This is a good, functioning start, but I'd like for the `form_builder` to just be a core part of Lynx. We can develop both parts of the app -- the "run form" component and the "build form" component dependent on the same configuration, but we can always pull that out into our application as needed.

**Comment by foresttoney** [comment]
I don't know if we are going to want the form builder to live here long term. I suppose this is fine for now.

**Comment by thomashoneyman** [comment]
You're right, the UI for the builder ought to live only as an example here (or dev), but ultimately will be in the application.

**Comment by thomashoneyman** [comment]
Todo: 

1. Builder submit should serialize form and put to database
2. Builder should check db at form id to see if there's an existing form; if so, load it

**Comment by thomashoneyman** [comment]
These are finished. Merging.

**Pull request merged**
